# New iterative eigen

I Wayan Sudiarta, Ph.D.

6 2 22

Reference:
1. https://numpy.org/doc/stable/reference/generated/numpy.matrix.html


In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import linalg as la

## Use Numpy For Matrix

In [63]:
# matrix H
H = np.matrix([[2, 0, 0],[0, 2, 1], [0, 1, 2]])
print(H)

[[2 0 0]
 [0 2 1]
 [0 1 2]]


In [60]:
w, v = la.eig(H)

In [61]:
w

array([6., 2., 4.])

In [49]:
v

matrix([[ 0.70710678, -0.70710678,  0.        ],
        [ 0.70710678,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ]])

In [6]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
E = 2.5
n  = 100
G = I - (1.0/(E*n))*H

In [35]:
print(G)

[[ 0.992  0.     0.   ]
 [ 0.     0.992 -0.004]
 [ 0.    -0.004  0.992]]


In [36]:
G5 = G@G@G@G@G
G10 = G5@G5
G50 = G10@G10@G10@G10@G10
G100 = G50@G50

In [37]:
G100

matrix([[ 0.44788572,  0.        ,  0.        ],
        [ 0.        ,  0.4843993 , -0.18538327],
        [ 0.        , -0.18538327,  0.4843993 ]])

In [38]:
HG = H@G100

In [39]:
phi = np.random.rand(3,1)
for i in range(200):
    psi = HG@phi
    phi = psi/la.norm(psi)
    en = np.transpose(phi)@H@phi
    print(i, en.item())
    

0 2.345928533153458
1 2.4367374795474417
2 2.4932146556313377
3 2.526988748920191
4 2.5468029124269087
5 2.5583851884040536
6 2.565227545892648
7 2.56937708596757
8 2.572008265590198
9 2.5737868715986867
10 2.5750878245327185
11 2.576121468049764
12 2.577005567600226
13 2.57780597997512
14 2.5785595092926514
15 2.5792867156134913
16 2.5799990816653695
17 2.5807030192766662
18 2.5814021080054688
19 2.582098345649165
20 2.582792846677699
21 2.583486232287753
22 2.5841788482255885
23 2.584870886425078
24 2.585562452932452
25 2.586253605836236
26 2.5869443764476
27 2.5876347811275875
28 2.5883248278914652
29 2.589014520096625
30 2.589703858501906
31 2.5903928424175406
32 2.5910814703472886
33 2.5917697403470186
34 2.5924576502249503
35 2.5931451976534907
36 2.5938323802316896
37 2.594519195520129
38 2.5952056410604243
39 2.5958917143861284
40 2.5965774130288284
41 2.5972627345215726
42 2.5979476764007927
43 2.5986322362073944
44 2.599316411487381
45 2.6000001997922118
46 2.600683598679024


In [13]:
phi

matrix([[4.11274535e-05],
        [7.07106781e-01],
        [7.07106781e-01]])

In [14]:
psin = psi/la.norm(psi)

In [15]:
psin

matrix([[4.11274535e-05],
        [7.07106781e-01],
        [7.07106781e-01]])

In [16]:
np.transpose(psin)@H@psin

matrix([[3.]])

In [17]:
w, v = la.eig(HG)

In [18]:
w

array([1.09809702, 0.71613246, 1.02454475])

In [19]:
v

matrix([[ 0.        ,  0.        ,  1.        ],
        [ 0.70710678,  0.70710678,  0.        ],
        [ 0.70710678, -0.70710678,  0.        ]])

In [20]:
3*np.exp(-3/2)

0.6693904804452895